import i1 from '../images/CatalogoDS-13.jpg'
import i2 from '../images/CatalogoDS-13.jpg'
import i3 from '../images/CatalogoDS-14.jpg'
import i4 from '../images/CatalogoDS-15.jpg'
import i5 from '../images/CatalogoDS-16.jpg'
import i6 from '../images/CatalogoDS-17.jpg'
import i7 from '../images/CatalogoDS-18.jpg'
import i8 from '../images/CatalogoDS-19.jpg'
import i9 from '../images/CatalogoDS-20.jpg'
import i10 from '../images/CatalogoDS-21.jpg'
import i11 from '../images/CatalogoDS-22.jpg'
import i12 from '../images/CatalogoDS-23.jpg'
export const listProduct=[
    {
        id:'0001',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i1,
        price: 1000,
        offer: true,
        category:'Desayunos',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',

    },
    {
        id:'0002',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i2,
        price: 1000,
        offer: false,
        category:'Desayunos',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',

    },
    {
        id:'0003',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i3,
        price: 1000,
        offer: true,
        category:'Desayunos',
        rating: 5,
        reviews: 10,

    },
    {
        id:'0004',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i4,
        price: 1000,
        offer: true,
        category:'Desayunos',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    },
    {
        id:'0005',
        name:'name1',
        desc:'Este producto es espectacular¡Delicioso desayuno para empezar el día con energía! Nuestro irresistible combo incluye una suculenta tortilla de huevos, crujientes tostadas de pan integral, y jugosas rodajas de fruta fresca. Disfruta de una experiencia matutina llena de sabor y nutrientes. ¡El desayuno perfecto para conquistar el día!',
        img: i5,
        price: 1000,
        offer: true,
        category:'Detalles',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    },
    {
        id:'0006',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i6,
        price: 1000,
        offer: true,
        category:'Detalles',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    },
    {
        id:'0007',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i7,
        price: 1000,
        offer: true,
        category:'Detalles',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    },
    {
        id:'0008',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i8,
        price: 1000,
        offer: false,
        category:'Detalles',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    },
    {
        id:'0009',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i9,
        price: 1000,
        offer: true,
        category:'Detalles',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    },
    {
        id:'0010',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i10,
        price: 1000,
        offer: true,
        category:'Desayunos',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    },
    {
        id:'0011',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i11,
        price: 1000,
        offer: true,
        category:'Desayunos',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    },
    {
        id:'0012',
        name:'name1',
        desc:'Este producto es espectacular',
        img: i12,
        price: 1000,
        offer: true,
        category:'Detalles',
        rating: 5,
        reviews: 10,
        alt: 'mi nombre',
    }
]